####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                            __        ___   __       ___            ___                       | #
# |                           |__) |    /   \ /  ` |__/  |  |  | |\ | |__                        | #
# |                           |__) |___ \___/ \__, |  \  |  \__/ | \| |___                       | #
# |                                                                                              | #
# |                                      https://kubbidev.com                                    | #
# |                                                                                              | #
# |  DISCORD:     https://discord.kubbidev.com                                                   | #
# |  BUG REPORTS: https://github.com/kubbidev/BlockTune/issues                                   | #
# |                                                                                              | #
# |  New options are not added to this file automatically. Default values are used if an         | #
# |  option cannot be found.                                                                     | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################