####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                            __        ___   __       ___            ___                       | #
# |                           |__) |    /   \ /  ` |__/  |  |  | |\ | |__                        | #
# |                           |__) |___ \___/ \__, |  \  |  \__/ | \| |___                       | #
# |                                                                                              | #
# |                                      https://kubbidev.com                                    | #
# |                                                                                              | #
# |  DISCORD:     https://discord.kubbidev.com                                                   | #
# |  BUG REPORTS: https://github.com/kubbidev/BlockTune/issues                                   | #
# |                                                                                              | #
# |  New options are not added to this file automatically. Default values are used if an         | #
# |  option cannot be found.                                                                     | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                    CUSTOMIZATION SETTINGS                                    | #
# |                                                                                              | #
# |               Settings that allow admins to customize the way BlockTune operates.            | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# When set to true, passive spells must be bound in order to take effect otherwise, unlocked
# spells will take effect right away.
#
# This is only the default behavior for spells but can be overridden by specifying true/false
# to the "needs-bound" field in the profess spells section.
passive-spell-need-bound: true