####################################################################################################
# +----------------------------------------------------------------------------------------------+ #
# |                            __        ___   __       ___            ___                       | #
# |                           |__) |    /   \ /  ` |__/  |  |  | |\ | |__                        | #
# |                           |__) |___ \___/ \__, |  \  |  \__/ | \| |___                       | #
# |                                                                                              | #
# |                                      https://kubbidev.com                                    | #
# |                                                                                              | #
# |  DISCORD:     https://discord.kubbidev.com                                                   | #
# |  BUG REPORTS: https://github.com/kubbidev/BlockTune/issues                                   | #
# |                                                                                              | #
# |  New options are not added to this file automatically. Default values are used if an         | #
# |  option cannot be found.                                                                     | #
# +----------------------------------------------------------------------------------------------+ #
####################################################################################################

# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                    CUSTOMIZATION SETTINGS                                    | #
# |                                                                                              | #
# |               Settings that allow admins to customize the way BlockTune operates.            | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# Main number formatting separator symbol used in every decimal formatter across the plugin.
# Note: restart your server when changing this option to propagate changes
decimal-format-separator: .




# +----------------------------------------------------------------------------------------------+ #
# |                                                                                              | #
# |                                      FINE TUNING OPTIONS                                     | #
# |                                                                                              | #
# |     A number of more niche settings for tweaking and changing behaviour. The section also    | #
# | contains toggles for some more specialised features. It is only necessary to make changes to | #
# |                 these options if you want to fine-tune BlockTune behaviour.                  | #
# |                                                                                              | #
# +----------------------------------------------------------------------------------------------+ #

# +----------------------------------------------------------------------------------------------+ #
# | Game indicators settings                                                                     | #
# +----------------------------------------------------------------------------------------------+ #

# BlockTune can display indicators in the game for various reasons.
#
# Examples:
# - In the event of damage
# - When you're regenerating your life
game-indicators:
  # Indicators displayed when an entity suffers damage from any possible source.
  # Note: a server restart is required to propagate the changes.
  damage:
    # Whether or not BlockTune should display damage indicators.
    enabled: true

  # Indicators displayed when an entity regenerates its life in all possible ways.
  # Note: a server restart is required to propagate the changes.
  regeneration:
    # Whether or not BlockTune should display regeneration indicators.
    enabled: true

# +----------------------------------------------------------------------------------------------+ #
# | Interaction rules settings                                                                   | #
# +----------------------------------------------------------------------------------------------+ #

# Whether or not a player performing an offensive/support action can interact with another player.
# - This accounts for skills,
# - and a few other things
interaction-rules:
  # When enabled, apply PvP interaction rules for skills, melee and projectile hits
  # Note: This option is toggled off by default to reduce confusion for new users.
  enabled: true
  # When disabled, support-based skills (buffs or heals)
  # may only be applied onto players.
  support-skills-on-mobs: true
  pvp-off:
    offense:
      self: false
    support:
      party-member: true
      party-other: true
      guild-ally: true
      guild-neutral: true
      guild-enemy: true
      self: true
  pvp-on:
    offense:
      party-member: false
      guild-ally: false
      guild-neutral: true
      self: false
    support:
      party-member: true
      party-other: false
      guild-ally: true
      guild-neutral: true
      guild-enemy: false
      self: true